#!/usr/bin/env bash

set -Eeuo pipefail # https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

TRAVIS_OSX_IMAGE="${TRAVIS_OSX_IMAGE:-}"
DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-}"

function init_ubuntu_keyring() {
  sudo apt-get install -y gnome-keyring
  sudo apt-get install -y python-gnomekeyring
  # see https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728 :
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157

  if command -v dbus-launch >/dev/null; then
    if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then eval `dbus-launch --sh-syntax`; fi
    dbus-launch /usr/bin/python -c "import gnomekeyring;gnomekeyring.create_sync('login', '');"
  fi
}

function brew_uninstall() {
  brew cleanup
  URL='https://raw.githubusercontent.com/Homebrew/install/master/uninstall'
  curl -sLO "${URL}"
  chmod +x uninstall
  ./uninstall --force
  rm -rf /usr/local/Homebrew
  sudo rm -rf /usr/local/Caskroom
  sudo rm -rf /usr/local/bin/brew
  sudo rm -rf /Library/Developer/CommandLineTools
}

function main() {
  bin/strap run && bin/strap run
  bin/strap run --with-hook-package='com.github.lhazlewood:strap-hello' # call with a package
  STRAP_INTERACTIVE=false bin/strap lansible --role='lhazlewood/ansible-role-test' # call with an ansible role
  pushd "${TRAVIS_BUILD_DIR}/test" > /dev/null
    STRAP_INTERACTIVE=false "${TRAVIS_BUILD_DIR}/bin/strap" lansible
  popd > /dev/null
  STRAP_INTERACTIVE=false bin/strap lansible --playbook="${TRAVIS_BUILD_DIR}/tests/.strap/ansible/playbooks/default"
}
main
