#!/usr/bin/env bash

STRAP_RELEASE_REF="${STRAP_RELEASE_REF:-}"
[[ -z "$STRAP_RELEASE_REF" ]] && STRAP_RELEASE_REF='master'
export STRAP_RELEASE_REF # make available to the install script

STRAP_INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/ultimatedotfiles/strap/${STRAP_RELEASE_REF}/install"

if command -v wget >/dev/null; then
  wget -qO- "$STRAP_INSTALL_SCRIPT_URL" | bash
elif command -v curl >/dev/null; then
  curl -fsSL "$STRAP_INSTALL_SCRIPT_URL" | bash
else
  echo "Neither wget nor curl are available.  Cannot download strap." >&2
  exit 1
fi

exepath=".strap/releases/current/bin/strap"
strapexe="$HOME/$exepath"

if [[ ! -x "$strapexe" ]]; then
  echo "Strap installation likely failed: Could not find '\$HOME/$exepath'." >&2
  exit 1
fi

"$strapexe" lansible "$@"
