#!/usr/bin/env bash

set -Eeuo pipefail # https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

STRAP_DEBUG="${STRAP_DEBUG:-}" && [[ -n "$STRAP_DEBUG" ]] && set -x
[[ "$(whoami)" != "root" ]] && echo "This script must be run via sudo." >&2 && exit 1

file="/etc/sudoers"

# If strap set something, remove it:
if grep -q '^## strap:begin$' "$file" && grep -q '^## strap:end$' "$file"; then
  sed -i '' '/## strap:begin/,/## strap:end/d' "$file"
fi

# remove any blank lines at end of the file:
#sed -i '' -e :a -e '/^\n*$/{\$d;N;};/\n\$/ba' "$file"