#!/usr/bin/env bash
set -e
[ -n "$STRAP_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

resolvepath() {
  local cwd="$(pwd)"
  cd $1
  echo "$(pwd)"
  cd "$cwd"
}

samedir()  {
  if [ -d $1 ] && [ -d $2 ]; then
  local path1="$(resolvepath $1)"
  local path2="$(resolvepath $2)"

  if [ $path1 == $path2 ]; then
   return 0;
  else
   return 1;
  fi
fi
return 0;
}

if [ -z "${STRAP_ROOT}" ]; then
  STRAP_ROOT="${HOME}/.strap"
else
  STRAP_ROOT="${STRAP_ROOT%/}"
fi
export STRAP_ROOT


if [ -z "${STRAP_DIR}" ]; then
  STRAP_DIR="$(pwd)"
else
  cd "$STRAP_DIR" 2>/dev/null || {
    echo "strap: cannot change working directory to '$STRAP_DIR'"
    exit 1
  } >&2
  STRAP_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export STRAP_DIR

shopt -s nullglob


bin_path="$(abs_dirname "$0")"

if ! samedir "${STRAP_ROOT}" "$bin_path/../"  ; then
   STRAP_INSTALL_DIR=$(resolvepath "$bin_path/../")
else
    STRAP_INSTALL_DIR=$STRAP_ROOT
fi
export STRAP_INSTALL_DIR


# Plugins
for plugin_bin in "${STRAP_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"


# Hooks
hook_path="${STRAP_HOOK_PATH}"
for plugin_hook in "${STRAP_ROOT}/plugins/"*/etc/strap.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export STRAP_HOOK_PATH="$hook_path"

shopt -u nullglob

command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "strap version $(strap version)\n$(strap-help)" >&2
  ;;
"-v" | "--version" )
  echo -e "strap version $(strap version)" >&2
  ;;
* )
  command_path="$(command -v "strap-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "strap: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac